owner: ss-o
repo: upptime
sites:
  - name: Play
    url: $SECRET_SITE_1
  - name: Music
    url: $SECRET_SITE_2
  - name: Code
    url: $SECRET_SITE_3
  - name: Digital-Link
    url: $SECRET_SITE_4
  - name: HEAD
    method: HEAD
    url: $SECRET_SITE_5
  - name: TCP ping
    url: 1.1.1.1

status-website:
  cname: up.w-ss.io
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Domain **w-ss.io** uptime.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
# See https://upptime.js.org/docs/configuration
