owner: ss-o
repo: upptime
sites:
  - name: DNS DEV
    url: 157.245.29.132
  - name: DEV W-SS
    url: 46.101.65.57
  - name: W-SS HTTPS
#    url: https://w-ss.io
#  - name: DigitalClouds HTTPS
#    url: https://digitalclouds.dev
#  - name: Digitally HTTPS
#    url: https://digitally.ink
#  - name: Digitals HTTPS
#    url: https://digitals.pw
  - name: TCP ping
    url: 1.1.1.1

status-website:
  cname: up.w-ss.io
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Domain **w-ss.io** uptime.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
# See https://upptime.js.org/docs/configuration
