# Change these first
owner: ss-o # Your GitHub username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: Code
    url: $SECRET_SITE_1
  - name: Subspace
    url: $SECRET_SITE_2
  - name: Files
    url: $SECRET_SITE_3
  - name: Portainer
    url: $SECRET_SITE_4
  - name: Yacht
    url: $SECRET_SITE_5
  - name: Ghost
    url: $SECRET_SITE_6
  - name: Heimdall
    url: $SECRET_SITE_7
  - name: Home
    url: $SECRET_SITE_8
  - name: Jellyfin
    url: $SECRET_SITE_9
  - name: Navidrome
    url: $SECRET_SITE_10
  - name: HEAD
    method: HEAD
    url: https://w-ss.io
  - name: TCP ping
    url: 1.1.1.1

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # Uncomment the following line if you don't have a custom domain and add your repo name
  cname: up.w-ss.io
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Domain **w-ss.io** uptime.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
