owner: ss-o
repo: upptime
sites:
#  - name: W-SS 
#    url: https://w-ss.io
#  - name: DigitalClouds 
#    url: https://digitalclouds.dev
#  - name: Digitally 
#    url: https://digitally.ink
  - name: Jellyfin
    url: https://jellyfin.w-ss.io
  - name: Data container
    url: https://data.w-ss.io
  - name: TCP ping
    url: 1.1.1.1

status-website:
  theme: dark
  cname: up.w-ss.io
#  logoUrl: https://github.com/ss-o/ss-o.github.io/raw/master/static/img/ninja.png
  name: Digital Clouds
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Uptime status page.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
#     - title: Contact
#      href: https://github.com/$OWNER/$REP
# See https://upptime.js.org/docs/configuration
