owner: ss-o
repo: upptime
sites:
  - name: MANAGER_NODE
    url: $MANAGER_NODE
  - name: DIGITAL_NODE
    url: $DIGITAL_NODE
  - name: JELLYFIN
    url: $jELLYFIN
  - name: DPI
    url: $DPI
  - name: TCP ping
    url: 1.1.1.1

status-website:
  cname: up.w-ss.io
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Domain **w-ss.io** uptime.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
# See https://upptime.js.org/docs/configuration
