owner: ss-o
repo: upptime
sites:
  - name: Code
    url: $SECRET_SITE_1
  - name: Digital-link
    url: $SECRET_SITE_2
  - name: Files
    url: $SECRET_SITE_3
  - name: Portainer
    url: $SECRET_SITE_4
  - name: Yacht
    url: $SECRET_SITE_5
  - name: Ghost
    url: $SECRET_SITE_6
  - name: Heimdall
    url: $SECRET_SITE_7
  - name: Home
    url: $SECRET_SITE_8
  - name: Jellyfin
    url: $SECRET_SITE_9
  - name: Navidrome
    url: $SECRET_SITE_10
  - name: Do
    url: $SECRET_SITE_11    
  - name: HEAD
    method: HEAD
    url: https://get-digital.link
  - name: TCP ping
    url: 1.1.1.1

status-website:
  cname: up.w-ss.io
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Domain **w-ss.io** uptime.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
# See https://upptime.js.org/docs/configuration
