# Change these first
owner: ss-o # Your GitHub username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: Jellyfin
    url: https://jellyfin.w-ss.io
  - name: Subspace
    url: https://subspace.w-ss.io
  - name: Docker
    url: https://portainer.w-ss.io
  - name: Yacht
    url: https://yacht.w-ss.io
  - name: HEAD
    method: HEAD
    url: https://do.w-ss.io
  - name: Secret Site
    url: $SECRET_SITE
  - name: TCP ping
    url: 1.1.1.1

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # Uncomment the following line if you don't have a custom domain and add your repo name
  cname: up.w-ss.io
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Domain **w-ss.io** uptime.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
